export const tasks = [
  {
    id: 1,
    aircraftId: 1,
    order: 1,
    itemType: "section",
    description: "Pilot Qualifiations and Experience",
    riskValue: 5,
  },
  {
    id: 2,
    aircraftId: 1,
    order: 2,
    itemType: "task",
    description: "Less than 200 hours in type",
    riskValue: 5,
  },
  {
    id: 3,
    aircraftId: 1,
    order: 3,
    itemType: "task",
    description: "Less than 30 hours in last 90 days",
    riskValue: 5,
  },
  {
    id: 4,
    aircraftId: 1,
    order: 4,
    itemType: "task",
    description: "No type specific recurrent training in last 12 months",
    riskValue: 5,
  },
  {
    id: 5,
    aircraftId: 1,
    order: 5,
    itemType: "task",
    description: "“Duty day” that exceeds 14 hours",
    riskValue: 4,
  },

  {
    id: 6,
    aircraftId: 1,
    order: 6,
    itemType: "task",
    description: "Feeling tired, ill or under stress",
    riskValue: 5,
  },
  {
    id: 7,
    aircraftId: 1,
    order: 7,
    itemType: "task",
    description: "External pressure to complete a trip",
    riskValue: 5,
  },
  {
    id: 8,
    aircraftId: 1,
    order: 8,
    itemType: "section",
    description: "Operating Environment",
    riskValue: 9,
  },
  {
    id: 9,
    aircraftId: 1,
    order: 9,
    itemType: "task",
    description: "No published approach",
    riskValue: 3,
  },
  {
    id: 10,
    aircraftId: 1,
    order: 10,
    itemType: "task",
    description: "Instrument approach without vertical guidance",
    riskValue: 3,
  },
  {
    id: 11,
    aircraftId: 1,
    order: 11,
    itemType: "task",
    description: "Circling approach - day (night)",
    riskValue: 3,
  },
  {
    id: 12,
    aircraftId: 1,
    order: 12,
    itemType: "task",
    description: "No weather reporting at destination",
    riskValue: 5,
  },
  {
    id: 13,
    aircraftId: 1,
    order: 13,
    itemType: "task",
    description: "Alternate airport not selected",
    riskValue: 4,
  },
  {
    id: 14,
    aircraftId: 1,
    order: 14,
    itemType: "task",
    description: "Marginal weather at alternate",
    riskValue: 5,
  },
  {
    id: 15,
    aircraftId: 1,
    order: 15,
    itemType: "task",
    description: "Moderate to severe Icing conditions reported or forecast",
    riskValue: 5,
  },
  {
    id: 16,
    aircraftId: 1,
    order: 16,
    itemType: "task",
    description:
      "Thunderstorms, heavy rain, or severe turbulence reported or forecast",
    riskValue: 5,
  },

  {
    id: 17,
    aircraftId: 1,
    order: 17,
    itemType: "task",
    description: "Surface winds > 30 kts and/or crosswind > 15 kts",
    riskValue: 4,
  },

  {
    id: 18,
    aircraftId: 1,
    order: 18,
    itemType: "task",
    description: "Winter operation",
    riskValue: 3,
  },

  {
    id: 19,
    aircraftId: 1,
    order: 19,
    itemType: "task",
    description: "Night Operation",
    riskValue: 4,
  },

  {
    id: 20,
    aircraftId: 1,
    order: 20,
    itemType: "task",
    description: "High terrain surrounding airport",
    riskValue: 3,
  },

  {
    id: 21,
    aircraftId: 1,
    order: 21,
    itemType: "task",
    description:
      "Runway length < accelerate/stop distance (if unavailable: takeoff distance plus 1/2 landing distance)",
    riskValue: 2,
  },

  {
    id: 22,
    aircraftId: 1,
    order: 22,
    itemType: "task",
    description: "High density altitude and maximum gross weight takeoff",
    riskValue: 5,
  },

  {
    id: 23,
    aircraftId: 1,
    order: 23,
    itemType: "task",
    description: "Uncontrolled and/or unfamiliar airport",
    riskValue: 3,
  },

  {
    id: 24,
    aircraftId: 1,
    order: 24,
    itemType: "task",
    description: "Planned flight time into last hour of fuel",
    riskValue: 3,
  },

  {
    id: 25,
    aircraftId: 1,
    order: 25,
    itemType: "section",
    description: "Equipment",
    riskValue: 3,
  },
  {
    id: 26,
    aircraftId: 1,
    order: 26,
    itemType: "task",
    description: "New avionics installed within last 6 months",
    riskValue: 3,
  },

  {
    id: 27,
    aircraftId: 1,
    order: 27,
    itemType: "task",
    description: "First flight after maintenance",
    riskValue: 5,
  },

  {
    id: 28,
    aircraftId: 1,
    order: 28,
    itemType: "task",
    description: "First flight after 15 days of non-use and/or outside storage",
    riskValue: 3,
  },

  {
    id: 29,
    aircraftId: 1,
    order: 29,
    itemType: "task",
    description: "Known maintenance discrepancies",
    riskValue: 3,
  },

  {
    id: 30,
    aircraftId: 1,
    order: 30,
    itemType: "task",
    description: "Inop or no autopilot (approach capable) for IFR flight",
    riskValue: 4,
  },
  {
    id: 31,
    aircraftId: 1,
    order: 31,
    itemType: "task",
    description:
      "More than 6 months since last engine inspection by a certified aircraft mechanic",
    riskValue: 2,
  },
];
