// export const tasks = [
//   {
//     id: 1,
//     aircraftId: 1,
//     order: 1,
//     itemType: "task",
//     description: "Less than 200 hours in type",
//     riskValue: 5,
//   },
//   {
//     id: 2,
//     aircraftId: 1,
//     order: 6,
//     itemType: "task",
//     description: "Less than 30 hours in last 90 days",
//     riskValue: 5,
//   },
//   {
//     id: 3,
//     aircraftId: 1,
//     order: 2,
//     itemType: "task",
//     description: "No type specific recurrent training in last 12 months",
//     riskValue: 10,
//   },
//   {
//     id: 4,
//     aircraftId: 1,
//     order: 4,
//     itemType: "task",
//     description: "External pressure to complete a trip",
//     riskValue: 9,
//   },
//   {
//     id: 5,
//     description: "Less than 200 hours in type",
//     aircraftId: 2,
//     itemType: "task",
//     order: 1,
//     riskValue: 5,
//   },
//   {
//     id: 6,
//     description: "Less than 30 hours in last 90 days",
//     aircraftId: 2,
//     itemType: "task",
//     order: 2,
//     riskValue: 5,
//   },
//   {
//     id: 7,
//     aircraftId: 2,
//     order: 3,
//     itemType: "task",
//     description: "No type specific recurrent training in last 12 months",
//     riskValue: 5,
//   },
//   {
//     id: 8,
//     aircraftId: 2,
//     order: 4,
//     itemType: "task",
//     description: "“Duty day” that exceeds 14 hours",
//     riskValue: 4,
//   },
//   {
//     id: 9,
//     aircraftId: 2,
//     order: 5,
//     itemType: "task",
//     description: "Feeling tired, ill or under stress",
//     riskValue: 5,
//   },
//   {
//     id: 10,
//     aircraftId: 2,
//     order: 6,
//     itemType: "task",
//     description: "External pressure to complete a trip",
//     riskValue: 5,
//   },
//   {
//     id: 11,
//     aircraftId: 1,
//     description: "“Duty day” that exceeds 14 hours",
//     itemType: "task",
//     order: 3,
//     riskValue: 10,
//   },
// ];
